sudo: required

services:
  - docker

language: java

env:
  global:
    COMMIT=${TRAVIS_COMMIT::8}
    secure: "qIyppcLG1zAvMiGuHG0hTE8ks61L4z/Ck8913PoaSju8eKmdzIozV9OjzCUdwnMqrxr5+GPddUdSgeopiBrZNJkgNZY0dtE84UcJUVvrunMwT+icCIozPeCQqBq2we1r5ajhzd4LTofQB6vW9kU9OOlyBWLV912YCVLKjv+Xrj78UFkMrbQ3ySDZ0UnBuxfIQzGIzGUM4iGKUgSi1m49PKqJTKgoCRDpLaNZlzR40z5qpnTqonqDra7X/3/NOGhjyiYlfQ5Am3e94MvURKhqYnCOJYo49SO/TQdOXMi341LOQEqWKIBWG4fF+LRd/urF+O0YInQO4q0Dpry00jC7tTmZbDPZKt7Djnn2s2EhlXbpqscqCSqEQQSD+xAmKRfR9QnpfKtZTfVMLW8dMCCiXm7sllLC4MEDR0pEzd/MeNTqFWrFhxYuXsi3MB6/EX+/0uqPjtavHWfCXAXVUtuN0mAGxNvb92WzH2xSD0khAVag9QhxDRY5jymF2/Nfk8Ol6yo+EbJ811YP3rnvpwuvunlqCjkeymSMoQVD6HZN63uof1swyDz2vKN6siIcr3+E2OBs/MrVxFtc3wGvstpGp2AKBY0rHI4+Iba4H342heHJjeKwksLMez9zTa/nFY8p+5xDKnn5IdUA7LEvaSimPpKsoyKzmuZ1gZL/PJxcpSU="
    secure: "C7dpf59o41lzv7L/8DT5zI9mWB5T77lKYJIAb0qYNxrJayB4OsnRAEOlMxXD0F18kuWKiQq2KCrFZ906K4GmcJf1KnoxG6PXW9uWOC0lMoU9oLiSSU+rl50cF+lfs0T0WvrgWlQFZaiPoxyqnOrqAwVFHG3jOAW+fKlcFyhZ/o/z33x8TNt2kRM+vnMM7h7InLbvT2bR7AZvKTmiwFl1lsnmTAv2Qw75CkVGKfDAygDIfHoG9nE5A67CaX/qJ/yavQrA0zxJYslElcy46HKIuADUJp/otNgD+c6zMxaM7ZcTzd9pDpJaw3ijA7gHTlDegqPNA1DeMbQNezTR0hU0pDMj90/xHIA7Qm1RE4rrqhJ2ICVo7GQQUTTZUz/Bp5hwGuXTEBH6UcLybWVNrxyAJfh3xSUsmm8YOVbAej8IUCESI6l24lDRdyZ3GQDWVOVhN2gPrB9ZZHYpRWTuAHk6RGw76rA0HeqhYTTBdBh5Z6SG5xhl8QPqmWhZS/MfJ/4kR5aIj8dBnRNd8aqye0i+20EM1OMIVrJfjpwUGbxpGYXjpz4838KJDrX4KqQXKtQPNSU0BubzmjeHsleef5G4taFG3g8VjgytwI5fDQh1oxorTj0j0Mf7XUToyXTHTZKnBsCVmT6pnt4ryuKQZER3NVLmATU9irYA6oH7wgoSw40="
    secure: "EkKnfpy6bUZ7IvTVWPw8y4dY9bzmWtr0vLpohfDpIvziUAeVVsRCIufRryBRRR6kkn6yHuPZs0WxcKgQP0TVCJVLuJ6A3Ayt9iy8EjnYUXZw1I9k/dF0x36l/3OiWoS9t4cA5eepuFPoUvXe+GChGeitoiIS8PZAEMswzltHpvVCYKVw9hze7k9v+D4Jaxdjnoo8JM2SPFTd1WnLiLOmw1eajSAApOoMxFquQwKGXYFj6ExzFrcBF90NWhE+BZ56u6HYrkcSacJLU66vEkRVca8nzuoEop083lOM66+Zd0MtERjkUBpiw2DpttDGhv+CFkypnaSjM1bS7TN8Cb8vp/RIzCw20qHzbEZFYiFnWQrUye5cnSfgTueXyAFhVXXpNrfgRM6uZz2iq8TtFAi/Ns4ij8exaZaaI2hg3F6RazvlxW6nPqJBI9dMkhGJ6DLIuMiWlrpzQqKcatjU75adH50OJLVJGcgJG0JkAumCcc/crQhSSUjeSGdXDq2/HhEuW3GuQnL17/GcbnhG328lbUfVUvMcsq6/znLK6JUza/wx9zZQo07NAeBiM7bbXRb02fa4OZG5xjyoSVKgexyJnqBkvJ3QZ/KQ0t5NnEy0SijChzxYJG1nafymGRs6o6euFnJz9auMxNqKSHxXnWqMIkal/wI2T3YnPk9jcMhVSe4="

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=openregister/certificate-transparency
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
